// 2020年下学期/Exercise/考核题汇总/2020.10月份月考_Vue/编程题/02-购物车/vue-cart/src/components/cartTotal.vue
<template>
<!-- 结算模板 -->
     <div class="total">
          <span>总价：{{price}}</span>
          <button>结算</button>
        </div>
</template>

<script>
export default {
    // 还不懂？？？？
    // 接收
 props: ["list"],
   computed: {
    //    计算价格
                price() {
                    var sum = 0
                    this.list.forEach(element => {
                        if (element.num < 0 || isNaN(element.num)) {
                            element.num = 0
                        }
                        sum += element.num * element.price
                    });
                    return sum
                }
            }
}
</script>

<style>

</style>

// 2021年上学期/React/React_day04品牌和购物车案例/cart/src/components/CartTotal/index.jsx
import React, { Component } from 'react'

export default class CartTotal extends Component {
    // 2.3.定义一个方法 用来计算总价

    computedTotal = () => {
        let sum = 0;
        this.props.list.forEach(item => {
            sum+=item.price*item.num
        })
        return sum
 }
    render() {
        return (
           <div className="total">
                <span>总价：{this.computedTotal()}</span>
          <button>结算</button>
        </div>
        )
    }
}
